worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout;
  error_log /dev/stderr warn;

  sendfile on;
  keepalive_timeout 65;

  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  upstream frontend_upstream {
    server 127.0.0.1:3000;
  }

  upstream backend_upstream {
    server 127.0.0.1:4000;
  }

  server {
    listen 80;
    server_name local.austenstrine.dssh;

    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name local.austenstrine.dssh;

    ssl_certificate /app/certs/local.austenstrine.dssh.crt;
    ssl_certificate_key /app/certs/local.austenstrine.dssh.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location /api/ {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_pass http://backend_upstream;
    }

    location / {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_pass http://frontend_upstream;
    }
  }
}