import { showcasePortals } from '../../lib/showcasePortals';

export function FeaturedBuildSection() {
	return (
		<section
			id="featured-build"
			className="
				rounded-2xl
				border
				border-slate-200
				bg-white
				p-8
				shadow-sm
			"
		>
			<div className="flex flex-col gap-3">
				<p
					className="
						text-xs
						font-semibold
						uppercase
						tracking-[0.22em]
						text-sky
					"
				>
					Featured builds
				</p>
				<h2
					className="
						text-3xl
						font-semibold
						text-ink
					"
				>
					Live marketplace portals
				</h2>
				<p
					className="
						max-w-3xl
						text-slate-700
					"
				>
					These are working surfaces, not mocks. Start from an empty database with the guided
					walkthrough, or jump into any create/manage page directly.
				</p>
			</div>

			<div
				className="
					mt-6
					grid
					gap-4
					md:grid-cols-2
				"
			>
				{showcasePortals.map((portal) => (
					<article
						key={portal.id}
						className="
							flex
							flex-col
							rounded-xl
							border
							border-slate-200
							bg-slate-50
							p-5
						"
					>
						<p
							className="
								text-[11px]
								font-semibold
								uppercase
								tracking-[0.18em]
								text-slate-500
							"
						>
							{portal.label}
						</p>
						<h3
							className="
								mt-1
								text-lg
								font-semibold
								text-ink
							"
						>
							{portal.title}
						</h3>
						<p
							className="
								mt-3
								flex-1
								text-sm
								text-slate-700
							"
						>
							{portal.summary}
						</p>
						<ul
							className="
								mt-4
								flex
								flex-col
								gap-1
								text-xs
								text-slate-600
							"
						>
							{portal.notes.map((note) => (
								<li key={note}>· {note}</li>
							))}
						</ul>
						<a
							href={portal.href}
							className="
								mt-5
								inline-flex
								self-start
								rounded-full
								bg-ink
								px-4
								py-2
								text-sm
								font-semibold
								text-white
								transition
								hover:-translate-y-0.5
								hover:bg-sky
							"
						>
							{portal.cta}
						</a>
					</article>
				))}
			</div>
		</section>
	);
}
