name: Deploy to EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          eval $(ssh-agent -s)
          ssh-add private_key || { echo "ssh-add failed with exit code $?"; exit 1; }
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || { echo "ssh-keyscan failed with exit code $?"; exit 1; }
          echo "Deploying to EC2"
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            mkdir -p ${{ secrets.TARGET_DIR }} &&
            cd ${{ secrets.TARGET_DIR }} &&
            if [ -d .git ]; then
              sudo git pull origin master;
            else
              sudo rm -rf * &&
              sudo git clone https://github.com/austenstrine/austenstrine_portfolio.git .;
            fi
          "