name: Deploy to EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          eval $(ssh-agent -s)
          ssh-add private_key
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          echo "Deploying to EC2"
          echo "EC2_USER: ${{ secrets.EC2_USER }}"
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "TARGET_DIR: ${{ secrets.TARGET_DIR }}"
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            mkdir -p ${{ secrets.TARGET_DIR }} &&
            cd ${{ secrets.TARGET_DIR }} &&
            git pull origin master
          "