name: Deploy to EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          eval $(ssh-agent -s)
          ssh-add private_key || { echo "ssh-add failed with exit code $?"; exit 1; }
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || { echo "ssh-keyscan failed with exit code $?"; exit 1; }
          echo "Deploying to EC2"
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            sudo mkdir -p ${{ secrets.TARGET_DIR }} &&
            sudo chown www-data:www-data ${{ secrets.TARGET_DIR }} &&
            cd ${{ secrets.TARGET_DIR }} &&
            if [ -d .git ]; then
              sudo -u www-data git pull origin master;
            else
              sudo -u www-data rm -rf * &&
              sudo -u www-data git clone https://github.com/austenstrine/austenstrine_portfolio.git .;
            fi
          "